# db config
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/todo
    username: root
    password: green502
    jdbc-url: jdbc:mariadb://localhost:3306/todo

# mybatis config
mybatis:
  type-aliases-package: com.green.todoapp.model
  mapper-locations: mapper/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/download/todo/

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://localhost:3306/todo_test
  sql:
    init:
      mode: always
      schema-locations: init/schema.sql
      data-locations: init/data.sql



